version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: eldercomp_postgres
    environment:
      POSTGRES_DB: eldercomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./schemas:/docker-entrypoint-initdb.d/schemas
    networks:
      - eldercomp_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eldercomp"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: eldercomp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eldercomp.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - eldercomp_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  eldercomp_network:
    driver: bridge
